name: Preprocess Dataset

on:
  push:
    paths:
      - "breast_cancer_raw/**"
      - "preprocessing/**"
      - ".github/workflows/preprocess.yml"
  workflow_dispatch:

jobs:
  preprocess:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install pandas scikit-learn

      - name: Run preprocessing
        run: python preprocessing/automate_Muhammad-Surya-Saputro.py

      - name: Upload processed dataset artifact
        uses: actions/upload-artifact@v4
        with:
          name: breast-cancer-preprocessing
          path: preprocessing/breast_cancer_preprocessing

